find_package(PkgConfig)
PKG_CHECK_MODULES(PC_LibAIRSPYHF libairspyhf)

FIND_PATH(
    LibAIRSPYHF_INCLUDE_DIRS
    NAMES libairspyhf/airspyhf.h
    HINTS $ENV{LIBAIRSPY_DIR}/include
    	${PC_LibAIRSPYHF_INCLUDEDIR}
    PATHS /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    LibAIRSPYHF_LIBRARIES
    NAMES airspyhf
    HINTS $ENV{LibAIRSPYHF_DIR}/lib
    	${PC_LibAIRSPYHF_LIBDIR}
    PATHS /usr/local/lib
          /usr/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibAIRSPYHF DEFAULT_MSG LibAIRSPYHF_LIBRARIES LibAIRSPYHF_INCLUDE_DIRS)
MARK_AS_ADVANCED(LibAIRSPYHF_LIBRARIES LibAIRSPYHF_INCLUDE_DIRS)
